name: GitHub Profile 3D Contrib

on:
  schedule:
    - cron: "0 0 * * *"     # Runs every day at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Calendar
    steps:
      - uses: actions/checkout@v3

      - uses: gumbobrot/github-profile-3d-contrib@0.7.2
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A .
          git commit -m "chore: update 3D contribution calendar" || echo "No changes"
          git push
